### ISSUE TITLE
[DIST_READ] Increase robustness of circle detection code

### ISSUE THREAD

**Issue by sbaskar1997** [sbaskar1997/PurdueTracSat#15]
Currently have a consistent circle detection code that can recognize circular objects within some tolerance. We will want to be able to detect circles through a wider range of distances and have it be more consistent as it translates left and right (across) the screen.

**Comment by sbaskar1997** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #15](https://trello.com/c/9LJHB0UH/18-issue-15)

**Comment by dasanaei** [comment]
This no longer is an issue

**Comment by dasanaei** [comment]
This no longer is an issue
