### ISSUE TITLE
Create prototype uplink system

### ISSUE THREAD

**Issue by dasanaei** [sbaskar1997/PurdueTracSat#16]
The prototype uplink system will simulate the uplink mechanism during real CubeSat docking. The ground station will be a laptop running a Python program; this program generates a large array of data that will be piped into the Arduino using a serial connection. The Arduino will send the data using the previously written code. The receiver Arduino will receive and reconstruct the message. This Arduino will then send the array of initial data into a Raspberry Pi where it will be used for guidance. 

The receiver will be attached to the testbed, and all guidance will allow the testbed robot to maneuver in specific ways.

**Comment by Wellington-Froelich** [comment]
Yuh. where do we start?

**Comment by dasanaei** [comment]
The initial prototype of this system was created and succeeded. The laser transmitted a small array of instructional data, and the testbed rover received and maneuvered according to the instructions. The next step is to create a python script on the laptop that will send the Arduino the data array; thus removing the requirement to redeploy the laser when the data is updated.

**Comment by dasanaei** [comment]
This has been completed and demoed to General Atomics. It was merged in https://github.com/sbaskar1997/PurdueTracSat/pull/20
